### ISSUE TITLE
(intermediate value)(...) is not a function error in code immediately following index.js from object-path

### ISSUE THREAD

**Issue by ghost** [mariocasciaro/object-path#116]
![image](https://user-images.githubusercontent.com/65345366/134495265-8ae26058-28e0-4b31-96e6-85f789f27094.png)
Since upgrading object-path to 0.11.8 this error started appearing. 
I think it's because of the removed ; in index.js on https://github.com/mariocasciaro/object-path/commit/4f0903fd7c832d12ccbe0d9c3d7e25d985e9e884#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L306
![image](https://user-images.githubusercontent.com/65345366/134496118-c5ec4004-2da4-43a0-bc67-a98ce8357df5.png)
I am only using index.js in my project, could be an issue in other files as well.

**Comment by mariocasciaro** [comment]
Hi Hajdi
Where that `(function() {` at the end is coming from? It's not from `object-path` right?

**Comment by ghost** [comment]
No, it's from another package I have. But the problem originates from object-path, because it's not properly closed with a ; (at least in index.js which I'm using)
See this issue: https://stackoverflow.com/questions/42036349/uncaught-typeerror-intermediate-value-is-not-a-function 
Downgrading object path to 0.11.7 fixes the error.

The file you see has many plugins concatenated in a single app.js file, one of which is object-path's index.js

**Comment by ghost** [comment]
I think just adding a ; at https://github.com/mariocasciaro/object-path/blob/4f0903fd7c832d12ccbe0d9c3d7e25d985e9e884/index.js#L320 would stabilize the package.

**Comment by ghost** [comment]
I realized that the problem only occurs because I minify my app.js file. Object-path works when included separately and not minified: https://jsfiddle.net/hajdi_k/Lge47nwv/ (look in resources)
![image](https://user-images.githubusercontent.com/65345366/134506622-d24a8967-2cf7-4132-b552-17d122e8fb0d.png)


I see a lot of resources on the net for issues with semicolons and minification. Also see this comment (on a completely different repo but similar issue) https://github.com/dalelotts/angular-date-time-input/issues/21#issuecomment-249773398 .

I guess I can separate all files I concatenate with ; or a new line, before minifying.. My error now occured because index.js was followed by (function() { from another package. 

It would be nice to not have to do this, because this occurs only on this package (so far). Others might be experiencing this issue as well and it's a bit difficult to debug.

Closing, since I can handle it when minifying.
